site_name: bk's notebook

nav:
  - 主页: readme.md
  - 其他资料:
    - 怎样部署到github: 其他资料/怎样部署到Github.md
  - 主干课程: 
    - 概率论与数理统计:
      - 第一章: 概率论与数理统计/20230202.md
      - 第二章: 概率论与数理统计/20230203.md
      - 第三章: 概率论与数理统计/20230204.md
      - 第四章: 概率论与数理统计/20230205.md
      - 第五章: 概率论与数理统计/20230206.md
      - 第六章: 概率论与数理统计/20230213.md
      - 第七章: 概率论与数理统计/20230214.md
      - 第八章: 概率论与数理统计/20230215.md
    - 普通物理学2:
      - 考前三天补天: 普通物理学2/普物2.md
    - 计组:
      - lec1: 计组/lec1.md
    - DB:
      - lec1: 数据库系统/lec1.md
    - ADS:
      - lec1: ADS/lec1.md
      - lec2: ADS/lec2.md
      - lec4: ADS/lec4.md
  - LeetCode刷题笔记:
    - 动态规划: LeetCode刷题笔记/动态规划.md
    - 1.两数之和(easy): LeetCode刷题笔记/1两数之和.md
    - 2.两数相加(medium): LeetCode刷题笔记/2两数相加.md
    - 3.无重复字符的最长子串(medium): LeetCode刷题笔记/3无重复字符的最长子串.md
    - 4.寻找两个正序数组的中位数(hard): LeetCode刷题笔记/4寻找两个正序数组的中位数.md
    - 5.最长回文子串(medium): LeetCode刷题笔记/5最长回文子串.md
    - 10.正则表达式匹配(hard): LeetCode刷题笔记/10正则表达式匹配.md
    - 11.盛最多水的容器(medium): LeetCode刷题笔记/11盛最多水的容器.md
    - 15.三数之和(medium): LeetCode刷题笔记/15三数之和.md
  - 图形学:
    - SSR算法小记: 图形学/SSR算法小记(Screen-Space-Reflection).md
  - 侯捷cpp:
    - 如何优雅地写一个类: 跟侯捷学cpp/如何优雅地写一个类.md
theme:
  name: material
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    - navigation.indexes
  palette: 
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

repo_url: https://github.com/Tianjiangyigeyi
repo_name: Tianjiangyigeyi

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
